name: Reconciliation_Tool
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - google-auth>=2.23.0
    - google-auth-oauthlib>=1.1.0
    - google-auth-httplib2>=0.1.1
    - google-api-python-client>=2.100.0
    - gspread>=5.11.0
    - pandas>=2.1.0